import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import NavBar from "./_components/NavBar/NavBar";
import About from "./_components/About";
import Landing from "./_components/Landing";
import MySkills from "./_components/MySkills/MySkills";
import MyProjects from "./_components/MyProjects/MyProjects";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={ubuntu.className + " bg-blue-100 text-white relative"}>
        <NavBar />
        <Landing />
        <About />
        <MySkills />
        <MyProjects />
        {children}
      </body>
    </html>
  );
}
